plugins {
	id 'java'
	id 'java-library'
}

dependencies {
    implementation project(':crnk-meta')
    implementation project(':crnk-client')
    implementation project(':crnk-gen:crnk-gen-base')

	implementation 'guru.nidi:graphviz-java:0.18.1'
    // todo #43826 switch to official swagger dependencies once they are available. See: https://github.com/swagger-api/swagger-core/pull/5031
	implementation "io.github.vpelikh:swagger-integration-jakarta:$VPELIKH_SWAGGER_VERSION"
	implementation "io.github.vpelikh:swagger-core-jakarta:$VPELIKH_SWAGGER_VERSION"
    implementation "io.github.vpelikh:swagger-models-jakarta:$VPELIKH_SWAGGER_VERSION"

    testImplementation 'commons-io:commons-io:2.14.0'
    testImplementation  project(':crnk-meta')
    testImplementation  project(':crnk-test')
    testImplementation  project(':crnk-format:crnk-format-plain-json')
}

test {
    testLogging.showStandardStreams = true
}

// implementation generated openapi files
tasks.test.doFirst {
    delete 'build/tmp/openapi'
}
