plugins {
	id 'java'
	id 'java-library'
}

dependencies {
    implementation project(':crnk-meta')
    implementation project(':crnk-client')
    implementation project(':crnk-gen:crnk-gen-base')

	implementation 'guru.nidi:graphviz-java:0.18.1'
	implementation "io.swagger.core.v3:swagger-integration-jakarta:$SWAGGER_VERSION"
	implementation "io.swagger.core.v3:swagger-core-jakarta:$SWAGGER_VERSION"
    implementation "io.swagger.core.v3:swagger-models-jakarta:$SWAGGER_VERSION"
	implementation 'io.swagger.parser.v3:swagger-parser:2.1.42'

    testImplementation 'commons-io:commons-io:2.14.0'
    testImplementation  project(':crnk-meta')
    testImplementation  project(':crnk-test')
    testImplementation  project(':crnk-format:crnk-format-plain-json')
}

test {
    testLogging.showStandardStreams = true
}

// implementation generated openapi files
tasks.test.doFirst {
    delete 'build/tmp/openapi'
}
