plugins {
	id 'java'
	id 'java-library'
	id 'org.springframework.boot' version "$SPRING_BOOT_VERSION"
	id 'io.spring.dependency-management'
}

dependencies {

	implementation project(':crnk-setup:crnk-setup-servlet')
	api project(':crnk-client')

	compileOnlyApi "org.springframework.boot:spring-boot-starter-web:$SPRING_BOOT_VERSION"
	compileOnlyApi "org.springframework.boot:spring-boot-configuration-processor:$SPRING_BOOT_VERSION"
	compileOnlyApi "org.springframework.boot:spring-boot-starter-actuator:$SPRING_BOOT_VERSION"
	compileOnlyApi 'org.springframework.security:spring-security-core'
	compileOnlyApi "org.hibernate.orm:hibernate-core:$HIBERNATE_CORE_VERSION"
	compileOnlyApi 'org.springframework:spring-orm'

	testImplementation  project(':crnk-data:crnk-data-jpa')
	testImplementation (project(':crnk-home')) {
		// Conflicts with Logback
		exclude group: 'org.slf4j', module: 'slf4j-simple'
	}
	testImplementation  project(':crnk-ui')
	testImplementation  project(':crnk-client')
	testImplementation  project(':crnk-test')
	testImplementation  'jakarta.el:jakarta.el-api:5.0.1'
	testImplementation  'org.glassfish:jakarta.el:5.0.0-M1'
	testImplementation  'com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-xml-provider:2.15.4'

	testImplementation  "org.springframework.boot:spring-boot-starter-data-jpa:$SPRING_BOOT_VERSION"
	testImplementation  "org.springframework.boot:spring-boot-starter-web:$SPRING_BOOT_VERSION"
	testImplementation  "org.springframework.boot:spring-boot-starter-test:$SPRING_BOOT_VERSION"
	testImplementation  "org.springframework.boot:spring-boot-starter-actuator:$SPRING_BOOT_VERSION"

	testImplementation "org.hibernate.orm:hibernate-core:$HIBERNATE_CORE_VERSION"
	testImplementation  'com.h2database:h2'

	testImplementation  "org.springframework.boot:spring-boot-configuration-processor:$SPRING_BOOT_VERSION"
	testImplementation  'org.springframework:spring-orm'
	testImplementation  'org.springframework.security:spring-security-core'

	bootJar {
		enabled = false
	}

	jar {
		enabled = true
		archiveClassifier = ''
	}
}


