plugins {
	id 'java'
	id 'java-library'
}

dependencies {
	implementation project(':crnk-core')
	compileOnly 'io.opentracing:opentracing-api:0.31.0'
	testImplementation  'io.opentracing:opentracing-api:0.31.0'
	testImplementation  project(':crnk-test')
	testImplementation  project(':crnk-setup:crnk-setup-servlet')

	testImplementation  "org.springframework:spring-test:$SPRING_FRAMEWORK_VERSION"
	testImplementation  "org.springframework:spring-web:$SPRING_FRAMEWORK_VERSION"
}
